### ISSUE TITLE
User Login 

### ISSUE THREAD

**Issue by helloJJ17** [ryoshi007/Confess-It#33]
![Screenshot 2022-06-12 112922](https://user-images.githubusercontent.com/105760097/173213163-ff2957cd-564a-42b7-bbf5-d045e8c008b9.png)
![Screenshot 2022-06-12 112912](https://user-images.githubusercontent.com/105760097/173213165-abdf9122-1a53-4d2e-ac26-5a229d72c1be.png)

**Comment by ryoshi007** [comment]
Please update sql table to these

Post table - 
![image](https://user-images.githubusercontent.com/74929046/173217403-ff7a9d39-8979-49c6-a227-7fc2d7ebfc85.png)

User table - 
![image](https://user-images.githubusercontent.com/74929046/173217415-7782bbd6-85e8-4c08-a816-b78ee07c5a86.png)
