### ISSUE TITLE
When user submit post

### ISSUE THREAD

**Issue by helloJJ17** [ryoshi007/Confess-It#36]
![Screenshot 2022-06-12 144308](https://user-images.githubusercontent.com/105760097/173222656-75624835-f369-412d-8a63-230840b78cb3.png)

This is the input.
this is a memory i realised just now. i met you much earlier, it was during sportrix. you have such a cool and bubbly personality. and you still do. this is my last prayer for you, i hope you will succeed in life and everafter. take care of yourself. thank you

**Comment by ryoshi007** [comment]
has been fixed with latest update
